-- 01
SELECT ENAME, LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 02
SELECT DNAME, SAL
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'ACCOUNTING';

-- 03
SELECT DNAME, SAL*12 AS "ANNUAL SALARY"
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL > 2340;

-- 04
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME LIKE '%A%';

-- 05
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'SALESMAN';

-- 06
SELECT DNAME, JOB
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB LIKE 'S%' AND DNAME LIKE 'S%';

-- 07
SELECT DNAME, MGR
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE MGR = 7839;

-- 08
SELECT DNAME, HIREDATE
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE >  '31-12-1983'
AND DNAME IN ('ACCOUNTING', 'RESEARCH');

-- 09
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE COMM IS NOT NULL AND COMM > 0
AND EMP.DEPTNO IN (10, 30);

-- 10
SELECT DNAME, EMPNO
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMPNO IN (7839, 7902)
AND LOC = 'NEW YORK';

-- 11
SELECT LOC, ROUND(AVG(SAL)) AS "AVERAGE SALARY"
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME NOT LIKE '_A%'
GROUP BY LOC;

-- 12
SELECT ENAME, LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'MANAGER' AND MGR = 7839;

-- 13
SELECT DNAME, EMPNO
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'CLERK' AND MGR IS NOT NULL;

-- 14
SELECT DNAME, SUM(SAL) AS "TOTAL SALARY"
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME
HAVING COUNT(*) > 3;

-- 15
SELECT DNAME, COUNT(*) AS "STRENGTH"
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB IN ('MANAGER', 'CLERK')
GROUP BY DNAME;

