-- 01
SELECT EMP.ENAME, EMP.JOB, EMP.SAL*12 AS "ANNUAL SAL", EMP.DEPTNO, DEPT.DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL*12 = 30000
AND JOB != 'CLERK';

-- 02
SELECT E1.ENAME AS "Employee Name",
E1.EMPNO AS "Employee Number",
E2.ENAME AS "Manager Name",
E2.EMPNO AS "Manager Number"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 03
SELECT ENAME, DNAME
FROM EMP RIGHT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 04
SELECT DNAME, SUM(SAL) AS "TOTAL SALARY"
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME;

-- 05
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 06
SELECT DISTINCT LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.COMM IS NOT NULL
AND EMP.COMM > 0;

-- 07
SELECT DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL = (SELECT MIN(SAL)
            FROM EMP)
AND MGR IS NULL;

SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE SAL = (SELECT MIN(SAL)
                            FROM EMP)
                AND MGR IS NULL);
-- 8
SELECT D1.DEPTNO, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.MGR = E2.EMPNO
AND E2.ENAME = 'SMITH';

-- 9
SELECT DISTINCT D3.DNAME, D3.LOC
FROM EMP E1, EMP E2, EMP E3, DEPT D3
WHERE E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO
AND E3.DEPTNO = D3.DEPTNO
AND E1.JOB = 'SALESMAN';

SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE EMPNO IN (SELECT MGR 
                              FROM EMP
                              WHERE EMPNO IN (SELECT MGR
                                            FROM EMP
                                            WHERE JOB = 'SALESMAN')));

-- 10
SELECT ENAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'RESEARCH'
AND JOB = 'MANAGER';

SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'RESEARCH')
AND JOB  = 'MANAGER';

-- 11
SELECT COUNT(*)
FROM  EMP E1, EMP E2, EMP E3
WHERE E1.MGR = E2.EMPNO
AND E1.ENAME = 'BLAKE'
AND E3.SAL < E2.SAL;

SELECT COUNT(*)
FROM EMP
WHERE SAL < (SELECT SAL
            FROM EMP
            WHERE EMPNO = (SELECT MGR
                          FROM EMP
                          WHERE ENAME = 'BLAKE'));

-- 14
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.SAL < (SELECT AVG(SAL)
                FROM EMP
                WHERE DEPTNO = 30);

-- 15
SELECT E1.ENAME, D1.DNAME, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.MGR = E2.EMPNO
AND D1.DEPTNO = E1.DEPTNO
AND E2.ENAME = 'JONES';

-- 16
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SUBSTR(ENAME, 1, 1) = 'S';

SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME LIKE 'S%';

-- 17
SELECT DNAME
FROM DEPT
WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO
                    FROM EMP);

SELECT DNAME
FROM EMP RIGHT OUTER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.EMPNO IS NULL;

-- 18
SELECT ENAME
FROM EMP
WHERE COMM IN (SELECT COMM
              FROM EMP
              GROUP BY COMM
              HAVING COUNT(*) > 1);

SELECT E1.ENAME, E1.EMPNO, E1.COMM
FROM EMP E1 INNER JOIN EMP E2
ON E1.COMM = E2.COMM
AND E1.EMPNO != E2.EMPNO
AND E1.COMM IS NOT NULL;

-- 19
SELECT DNAME, ENAME
FROM EMP RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 20
SELECT ENAME, JOB, DNAME, LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
AND EMP.JOB = 'MANAGER'
AND DEPT.LOC = 'CHICAGO';

-- 21
SELECT DISTINCT DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE BETWEEN '01-01-1981' AND '31-12-1982'
AND SAL > 1800;

-- 22
SELECT SAL
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
            FROM EMP
            WHERE SAL > (SELECT MIN(SAL)
                        FROM EMP));

SELECT E1.SAL
FROM EMP E1
WHERE 1 IN (SELECT COUNT(DISTINCT E2.SAL)
            FROM EMP E2
            WHERE E1.SAL >  E2.SAL);

-- 23
SELECT ENAME
FROM EMP
WHERE SAL*12 > 15000
AND HIREDATE < '01-01-1982';

-- 24
SELECT *
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE MGR IN (SELECT MGR
                            FROM EMP
                            GROUP BY MGR
                            HAVING COUNT(*) > 1));

-- 25
SELECT E1.ENAME AS "EMPLOYEE NAME",
E2.ENAME AS "MANAGER NAME"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 26
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME LIKE 'S%';

-- 27
SELECT E1.ENAME, E1.SAL
FROM EMP E1, EMP E2
WHERE E1.SAL = E2.SAL
AND E1.EMPNO <> E2.EMPNO;

SELECT ENAME
FROM EMP
WHERE SAL IN (SELECT SAL
              FROM EMP
              GROUP BY SAL
              HAVING COUNT(*) > 1);

-- 12
SELECT D1.DNAME, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.MGR = E2.EMPNO
AND E1.JOB = 'ANALYST'
AND E2.ENAME = 'BLAKE';

SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE JOB = 'ANALYST'
                AND MGR = (SELECT EMPNO
                          FROM EMP
                          WHERE ENAME = 'BLAKE'));

-- 13
SELECT E2.ENAME, E2.HIREDATE, E2.COMM
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.ENAME = 'FORD';
