-- 01
SELECT E1.ENAME, D1.DNAME, E2.SAL, D2.DNAME, E3.JOB, D3.DNAME
FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3
WHERE E1.DEPTNO = D1.DEPTNO
AND E2.DEPTNO = D2.DEPTNO
AND E3.DEPTNO = D3.DEPTNO
AND E1.DEPTNO = 10
AND E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO
AND E2.JOB IN ('PRESIDENT', 'MANAGER')
AND E3.SAL >= E2.SAL;

-- 02
SELECT E1.ENAME, D1.DNAME, E2.ENAME, D2.LOC, E3.ENAME, D3.LOC
FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3
WHERE E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.DEPTNO = D2.DEPTNO
AND E3.DEPTNO = D3.DEPTNO;

-- 03
SELECT D1.DNAME, E1.ENAME
FROM EMP E1 FULL OUTER JOIN DEPT D1
ON E1.DEPTNO = D1.DEPTNO;

-- 04
SELECT E1.ENAME, D1.DNAME, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.ENAME = 'SMITH';

-- 05
SELECT E1.ENAME, D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.SAL IN (SELECT E1.SAL
              FROM EMP E1
              GROUP BY E1.SAL
              HAVING COUNT(*) > 1);

-- 06
SELECT D1.DNAME AS "EMPLOYEE DEPT",
E1.ENAME AS "EMPLOYEE NAME",
E1.SAL AS "EMPLOYEE SAL"
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.ENAME = 'KING';

-- 07
SELECT E1.ENAME, E1.HIREDATE, E1.COMM, D1.DNAME, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.EMPNO = E2.MGR
AND E1.DEPTNO = D1.DEPTNO
AND E2.ENAME = 'FORD';

-- 08
SELECT DNAME, SUM(EMP.SAL)
FROM EMP INNER JOIN DEPT
ON DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DEPT.DNAME;
