-- 01
SELECT E1.ENAME, E1.JOB, E1.SAL*12 AS "ANNUAL SALARY", E1.DEPTNO, D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.SAL*12 > 30000
AND E1.JOB <> 'CLERK';

-- 02
SELECT 
E1.ENAME AS "EMPLOYEE NAME", 
E1.EMPNO AS "EMPLOYEE NUMBER", 
E2.ENAME AS "MANAGER NAME", 
E2.EMPNO AS "MANAGER NUMBER"
FROM EMP E1 JOIN EMP E2
ON E1.MGR = E2.EMPNO;

SELECT 
E1.ENAME AS "EMPLOYEE NAME", 
E1.EMPNO AS "EMPLOYEE NUMBER", 
E2.ENAME AS "MANAGER NAME", 
E2.EMPNO AS "MANAGER NUMBER"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 03
SELECT E1.ENAME, D1.DNAME
FROM DEPT D1 LEFT JOIN EMP E1
ON D1.DEPTNO = E1.DEPTNO;

-- 04
SELECT 
D1.DNAME AS  "DEPARTMENT", 
SUM(E1.SAL) AS "TOTAL SALARY"
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
GROUP BY D1.DNAME;

-- 05
SELECT E1.ENAME, D1.DNAME
FROM EMP E1, DEPT D1
WHERE D1.DEPTNO = E1.DEPTNO;

-- 06
SELECT DISTINCT D1.LOC
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.COMM > 0 AND E1.COMM IS NOT NULL;

-- 07
SELECT D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.MGR IS NULL
AND E1.SAL = (SELECT MIN(SAL)
              FROM EMP);

-- 08
SELECT D1.DNAME, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.MGR = E2.EMPNO
AND E2.ENAME = 'SMITH';

-- 09
SELECT DISTINCT D3.DNAME, D3.LOC
FROM EMP E1, EMP E2, EMP E3, DEPT D3
WHERE E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO
AND E3.DEPTNO = D3.DEPTNO
AND E1.JOB = 'SALESMAN';

-- 10
SELECT E1.ENAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND D1.DNAME = 'RESEARCH'
AND E1.JOB = 'MANAGER';

-- 11
SELECT COUNT(*)
FROM EMP
WHERE SAL < (SELECT SAL
            FROM EMP
            WHERE EMPNO = (SELECT MGR
                          FROM EMP
                          WHERE ENAME = 'BLAKE'));

-- 12
SELECT D1.DNAME, D1.LOC
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.MGR = E2.EMPNO
AND E1.JOB = 'ANALYST'
AND E2.ENAME = 'BLAKE';

SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE JOB = 'ANALYST'
                AND MGR = (SELECT EMPNO
                          FROM EMP
                          WHERE ENAME = 'BLAKE'));

-- 13
SELECT E1.ENAME, E1.HIREDATE, E1.COMM
FROM EMP E1, EMP E2
WHERE E1.EMPNO = E2.MGR
AND E2.ENAME = 'FORD';

-- 14
SELECT E1.ENAME, D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.SAL < (SELECT AVG(SAL)
              FROM EMP
              WHERE DEPTNO = 30);

-- 15
SELECT E1.ENAME, D1.DNAME, D1.LOC
FROM EMP E1, DEPT D1, EMP E2
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.ENAME  = 'JONES';

-- 16
SELECT E1.ENAME, D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.ENAME LIKE 'S%';

-- 17


-- 18
SELECT ENAME
FROM EMP
WHERE COMM = (SELECT COMM
              FROM EMP
              GROUP BY COMM
              HAVING COUNT(*) > 1);

-- 19
SELECT D1.DNAME, E1.ENAME
FROM DEPT D1 LEFT JOIN EMP E1
ON E1.DEPTNO = D1.DEPTNO;

-- 20
SELECT E1.ENAME, E1.JOB, D1.DNAME,  D1.LOC
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.JOB = 'MANAGER'
AND D1.LOC = 'CHICAGO';

-- 21
SELECT DISTINCT D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.HIREDATE BETWEEN '1-01-1981' AND '31-12-1982'
AND E1.SAL > 1800;

-- 22
SELECT E1.SAL
FROM EMP E1
WHERE 1 IN (SELECT COUNT(DISTINCT E2.SAL)
      FROM EMP E2
      WHERE E1.SAL > E2.SAL);

SELECT SAL
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
            FROM EMP
            WHERE SAL > (SELECT MIN(SAL)
                        FROM EMP));

-- 23
SELECT ENAME
FROM EMP
WHERE SAL*12 > 1500
AND HIREDATE < '01-01-1982';

-- 24
SELECT DISTINCT D1.DEPTNO, D1.LOC, D1.DEPTNO
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.MGR IN (SELECT MGR
              FROM EMP
              GROUP BY MGR
              HAVING COUNT(*) > 1);

-- 25
SELECT E1.ENAME AS "EMPLOYEE NAME",
E2.ENAME AS "MANAGER NAME"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 26
SELECT E1.ENAME, D1.DNAME
FROM EMP E1, DEPT D1
WHERE E1.DEPTNO = D1.DEPTNO
AND E1.ENAME LIKE 'S%';

-- 27
SELECT ENAME
FROM EMP
WHERE SAL IN (SELECT SAL
              FROM EMP
              GROUP BY SAL
              HAVING COUNT(*) > 1);