-- 2
SELECT DNAME, SAL
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME = 'ACCOUNTING';

-- 3
SELECT DNAME, SAL*12
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL > 2340;

-- 4
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DNAME LIKE '%A%';

-- 6
SELECT DNAME, JOB
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB LIKE 'S%'
AND DNAME LIKE 'S%';

SELECT DNAME, JOB
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SUBSTR(JOB, 1, 1)  = 'S'
AND SUBSTR(DNAME, 1, 1) = 'S';

-- 7
SELECT DNAME, MGR
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
AND MGR = 7839;


-- 8
SELECT DNAME, HIREDATE
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE HIREDATE >  '31-12-1983'
AND DNAME IN ('ACCOUNTING', 'RESEARCH');

-- 9
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE COMM IS NOT NULL AND COMM > 0
AND EMP.DEPTNO IN (10, 30);

-- 11
SELECT LOC, AVG(SAL)
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE ENAME NOT LIKE '_A'
GROUP BY LOC;

SELECT LOC, AVG(SAL)
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SUBSTR(ENAME, 2, 2) != 'A'
GROUP BY LOC;

-- 12
SELECT ENAME, LOC
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'MANAGER'
AND MGR = 7839;

-- 13
SELECT DNAME, EMPNO
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB = 'CLERK'
AND MGR IS NOT NULL;

-- 14
SELECT DNAME, SUM(SAL)
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DNAME
HAVING COUNT(*) > 3;

-- 15
SELECT DNAME, COUNT(*)
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE JOB IN ('MANAGER', 'CLERK')
GROUP BY DNAME;