-- 51
SELECT ENAME
FROM EMP
WHERE SAL > ANY (SELECT SAL
                FROM EMP
                WHERE JOB = 'SALESMAN');

-- 52
SELECT *
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE
                  FROM EMP
                  WHERE JOB = 'CLERK');

SELECT *
FROM EMP
WHERE HIREDATE > (SELECT MAX(HIREDATE)
                  FROM EMP
                  WHERE JOB = 'CLERK');

-- 53
SELECT ENAME, SAL
FROM EMP
WHERE SAL < ANY (SELECT SAL
                FROM EMP
                WHERE JOB = 'MANAGER');

-- 54
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < ALL (SELECT HIREDATE
                      FROM EMP
                      WHERE JOB = 'MANAGER');

-- 55
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE
                      FROM EMP
                      WHERE JOB = 'MANAGER')
AND SAL > ALL (SELECT SAL
              FROM EMP
              WHERE JOB = 'CLERK');

-- 41
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL) FROM EMP);

-- 43
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE) FROM EMP);

-- 44
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE) FROM EMP);

-- 45
SELECT ENAME, COMM
FROM EMP
WHERE COMM = (SELECT MIN(COMM)
              FROM EMP
              WHERE COMM > 0);

-- 49
SELECT *
FROM EMP
WHERE SAL*12 = (SELECT MIN(SAL*12)
                FROM EMP);

-- 81
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                GROUP BY DEPTNO
                HAVING COUNT(*) > 4);

-- 82
SELECT LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                GROUP BY DEPTNO
                HAVING COUNT(*) = 3);

-- 83
SELECT *
FROM EMP
WHERE SAL IN (SELECT SAL
            FROM EMP
            GROUP BY SAL
            HAVING COUNT(*) > 1);

-- 84
SELECT SAL
FROM EMP
WHERE ENAME IN (SELECT ENAME
                FROM EMP
                GROUP BY ENAME
                HAVING COUNT(*) > 1);

-- 85
SELECT *
FROM EMP
WHERE (SAL, DEPTNO) IN (SELECT SAL, DEPTNO
                        FROM EMP
                        GROUP BY SAL, DEPTNO
                        HAVING COUNT(*) > 1);

-- 86
SELECT *
FROM EMP
WHERE (HIREDATE, DEPTNO) IN (SELECT HIREDATE, DEPTNO
                        FROM EMP
                        GROUP BY HIREDATE, DEPTNO
                        HAVING COUNT(*) > 1);

-- 87
SELECT ENAME, SAL
FROM EMP
WHERE ENAME IN (SELECT ENAME
              FROM EMP
              GROUP BY ENAME
              HAVING COUNT(*) > 3);

-- 88
SELECT *
FROM EMP
WHERE (JOB, DEPTNO) IN (SELECT JOB, DEPTNO
                        FROM EMP
                        GROUP BY JOB, DEPTNO
                        HAVING COUNT(*) > 1);

-- 89
SELECT *
FROM EMP
WHERE (ENAME, JOB) IN (SELECT ENAME, JOB
                      FROM EMP
                      GROUP BY ENAME, JOB
                      HAVING COUNT(*) > 1);

-- 90
SELECT *
FROM EMP
WHERE EMPNO IN (SELECT MGR
              FROM EMP
              GROUP BY MGR
              HAVING COUNT(*) > 2);

-- 1
SELECT *
FROM 
    (SELECT EMP.*, ROWNUM AS "SLNO"
    FROM EMP)
WHERE SLNO = 3;

-- 2
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS SLNO
  FROM EMP)
WHERE SLNO <= (SELECT COUNT(*)/2
              FROM EMP);

-- 3
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE SLNO > (SELECT COUNT(*)-5
              FROM EMP);

-- 4
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE MOD(SLNO, 2) = 0;

-- 5
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS SLNO
  FROM EMP)
WHERE SLNO IN (5, 8, 11);

-- 6
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE MOD(SLNO, 2) != 0;

-- 7
SELECT *
FROM
  (SELECT ENAME, SAL, ROWNUM AS "SLNO"
  FROM
  (
    SELECT EMP.*
    FROM EMP
    ORDER BY SAL DESC
  ));

-- 8
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE MOD(SLNO, 3) = 0;

-- 9
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS SLNO
  FROM EMP)
WHERE SLNO BETWEEN 6 AND 10;

-- 10
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE SLNO > 5 AND SLNO < 11;

-- 11
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS SLNO
  FROM EMP)
WHERE SLNO >= (SELECT COUNT(*)*.90
              FROM EMP);

-- 12
SELECT *
FROM
  (SELECT ENAME, SAL, ROWNUM AS SLNO
  FROM 
    (SELECT *
    FROM EMP
    ORDER BY SAL DESC))
WHERE SLNO = 2;

-- 13
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE MOD(SLNO, 4) = 0;


-- 14
SELECT *
FROM EMP
WHERE ROWNUM = 1;

-- 15:
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE SLNO IN (2,3,5,7,11,13);

-- 1
SELECT UPPER(ENAME)
FROM EMP;

-- 2
SELECT LOWER(ENAME)
FROM EMP;

-- 3
SELECT REVERSE(ENAME)
FROM EMP;

-- 4
SELECT INITCAP(ENAME)
FROM EMP;

-- 5
SELECT LENGTH(ENAME)
FROM EMP;

-- 6
SELECT ENAME
FROM EMP
WHERE LENGTH(ENAME) > 5;

-- 7
SELECT SUBSTR(ENAME, 1, 3)
FROM EMP;

-- 8
SELECT SUBSTR(ENAME, -2, 2)
FROM EMP;

-- 9
SELECT *
FROM
  (SELECT ENAME, INSTR(ENAME, 'A', 1) AS "POSITION"
  FROM EMP);

-- 10
SELECT ENAME, REPLACE(ENAME,  'A', '@')
FROM EMP;

-- 11
SELECT ENAME, ROUND(SAL)
FROM EMP;

-- 18
SELECT UPPER(ENAME)
FROM EMP
WHERE ENAME LIKE '%S%';

-- 19
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME, 1, 1) = 'J'
AND LENGTH(ENAME) = 4;

-- 20
SELECT ENAME
FROM EMP
WHERE SUBSTR(ENAME, 2, 1) = 'A';


-- 01
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 02
SELECT DNAME, ENAME
FROM EMP RIGHT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 03
SELECT E1.ENAME AS "EMPLOYEE NAME",
E2.ENAME AS "MANAGER NAME"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 04
SELECT ENAME, DNAME
FROM EMP LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 05
SELECT DNAME
FROM DEPT LEFT JOIN EMP
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.EMPNO IS NULL;

-- 06
SELECT ENAME, DNAME
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

-- 07
SELECT E1.ENAME AS "EMPLOYEE NAME",
E2.ENAME AS "MANAGER NAME"
FROM EMP E1, EMP E2
WHERE E1.MGR = E2.EMPNO;

-- 08
SELECT DNAME, COUNT(*)
FROM DEPT LEFT JOIN EMP
ON DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DNAME;

-- 09
SELECT EMP.*
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DEPT.LOC = 'NEW YORK';

-- 10
SELECT ENAME, DNAME
FROM EMP LEFT JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT DNAME
FROM DEPT
WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO
                    FROM EMP);