-- 01
SELECT *
FROM
  (SELECT EMP.*, ROWNUM AS "SLNO"
  FROM EMP)
WHERE SLNO < 6;

-- 02
SELECT ENAME, SAL, SLNO
FROM
  (SELECT ENAME, SAL, ROWNUM AS "SLNO"
  FROM (
    SELECT *
    FROM EMP
    WHERE SAL > 5000
  ))
WHERE SLNO < 11;

-- 03
SELECT *
FROM
  (SELECT ENAME, SAL, ROWNUM AS "SLNO"
  FROM
  (
    SELECT *
    FROM EMP
    ORDER BY SAL DESC
  ))
WHERE SLNO < 4;

-- 04
SELECT *
FROM
  (SELECT ENAME, SAL, ROWNUM AS "SLNO"
  FROM
  (
    SELECT *
    FROM EMP
    ORDER BY SAL DESC
  ))
WHERE SLNO > 5 AND SLNO < 11;

-- 05
SELECT *
FROM
  (SELECT ENAME, DEPTNO, ROWNUM AS "SLNO"
  FROM
  (
    SELECT *
    FROM EMP
    WHERE DEPTNO = 90
  ))
WHERE SLNO < 8;

-- 06
SELECT *
FROM
  (SELECT ENAME, HIREDATE, ROWNUM AS "SLNO"
  FROM 
  (
    SELECT *
    FROM EMP
    WHERE HIREDATE > '01-01-2005'
  ))
WHERE SLNO < 6;

-- 07
SELECT *
FROM
  (SELECT ENAME, JOB, ROWNUM AS "SLNO"
  FROM
  (
    SELECT *
    FROM EMP
    WHERE JOB = 'SA_REP'
  ))
WHERE SLNO < 4;

-- 08
SELECT *
FROM (SELECT ENAME, SAL, ROWNUM AS "SLNO"
      FROM (SELECT *
            FROM EMP
            ORDER BY SAL DESC))
WHERE SLNO = 2;

-- 09

SELECT *
FROM (SELECT ENAME, ROWNUM AS "SLNO"
      FROM (SELECT *
            FROM EMP
            ORDER BY ENAME))
WHERE SLNO < 5;

-- 10
SELECT *
FROM (SELECT ENAME, HIREDATE, ROWNUM AS "SLNO"
      FROM (SELECT *
            FROM EMP
            ORDER BY HIREDATE))
WHERE SLNO = 5;

-- 3rd Record:

SELECT *
FROM (SELECT EMP.*, ROWNUM AS "SLNO"
      FROM EMP)
WHERE SLNO = 3;

-- First 50% record:
SELECT *
FROM (SELECT EMP.*, ROWNUM AS "SLNO"
      FROM EMP)
WHERE SLNO <= (SELECT COUNT(*)/2
              FROM EMP);

-- Last Five Records:
SELECT *
FROM (SELECT EMP.*, ROWNUM AS "SLNO"
      FROM EMP)
WHERE SLNO > (SELECT COUNT(*) - 5
              FROM EMP);

-- Even records:
SELECT *
FROM (SELECT EMP.*, ROWNUM AS "SLNO"
      FROM EMP)
WHERE MOD(SLNO, 2) = 0;

-- Odd Records:
SELECT *
FROM (SELECT EMP.*, ROWNUM AS "SLNO"
      FROM EMP)
WHERE MOD(SLNO, 2) != 0;

-- 5th, 8th and 11th Record:
SELECT *
FROM (SELECT EMP.*, ROWNUM AS "SLNO"
      FROM EMP)
WHERE SLNO IN (5, 8, 11);