-- 1
SELECT 
  E1.ENAME AS "EMPLOYEE NAME", 
  E2.ENAME AS "MANAGER NAME", 
  D1.LOC AS "EMPLOYEE LOCATION"
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E1.JOB = 'CLERK';

-- 2
SELECT
E1.ENAME AS "EMPLOYEE NAME",
E2.SAL AS "MANAGER SALARY",
D2.LOC AS "MANAGER LOCATION"
FROM EMP E1, EMP E2, DEPT D2
WHERE E1.MGR = E2.EMPNO
AND D2.DEPTNO = E2.DEPTNO
AND E2.JOB = 'PRESIDENT';

-- 3
SELECT
E1.ENAME AS "EMPLOYEE NAME",
E1.SAL AS "EMPLOYEE SALARY",
E2.ENAME AS "MANAGER NAME",
E2.SAL AS "MANAGER SALARY",
D1.DNAME AS "DEPARTMENT NAME"
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E1.SAL > E2.SAL;

-- 4
SELECT
E1.ENAME AS "EMPLOYEE NAME",
E1.SAL AS "EMPLOYEE SALARY",
E2.ENAME AS "MANAGER NAME",
D2.DNAME AS "DEPARTMENT NAME"
FROM EMP E1, EMP E2, DEPT D2
WHERE E1.MGR = E2.EMPNO
AND E2.DEPTNO = D2.DEPTNO
AND D2.LOC = 'NEW YORK' AND E2.SAL > 3000;

-- 5
SELECT
E1.ENAME AS "EMPLOYEE NAME",
D1.DNAME AS "DEPARTMENT",
E2.ENAME AS "MANAGER NAME",
D2.DNAME AS "DEPARTMENT"
FROM EMP E1, EMP E2, DEPT D1, DEPT D2
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.DEPTNO = D2.DEPTNO
AND D1.LOC = D2.LOC;

-- 6
SELECT
E1.ENAME AS "EMPLOYEE NAME",
E1.HIREDATE AS "EMPLOYEE HIREDATE",
E2.HIREDATE AS "MANAGER HIREDATE"
FROM EMP E1, EMP E2, DEPT D1
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.HIREDATE < E1.HIREDATE
AND D1.DNAME = 'ACCOUNTING';

-- 7
SELECT
E1.ENAME AS "EMPLOYEE NAME",
E2.ENAME AS "MANAGER NAME",
E3.ENAME AS "MANAGER'S MANAGER NAME"
FROM EMP E1, EMP E2, EMP E3
WHERE E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO;

-- 8
SELECT
E1.ENAME AS "EMPLOYEE NAME",
D1.DNAME AS "DEPARTMENT",
E2.ENAME AS "MANAGER NAME",
D2.DNAME AS "DEPARTMENT"
FROM EMP E1, EMP E2, DEPT D1, DEPT D2
WHERE E1.MGR = E2.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.DEPTNO = D2.DEPTNO
AND E2.HIREDATE < '01-01-1982';

-- 9
SELECT
E1.ENAME AS "EMPLOYEE NAME",
D1.DNAME AS "DEPARTMENT NAME",
E2.ENAME AS "MANAGER NAME",
D2.LOC AS "MANAGER LOCATION",
E3.ENAME AS "MANAGER'S MANAGER NAME",
D3.LOC AS "MANAGER'S MANAGER LOCATION"
FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3
WHERE E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.DEPTNO = D2.DEPTNO
AND E3.DEPTNO = D3.DEPTNO;

-- 10
SELECT
E1.ENAME AS "EMPLOYEE NAME",
D1.DNAME AS "DEPARTMENT NAME",
E2.SAL AS "MANAGER SALARY",
D2.DNAME AS "MANAGER DEPARTMENT",
E3.JOB AS "MANAGER'S MANAGER JOB",
D3.DNAME AS "MANAGER'S MANAGER DNAME"
FROM EMP E1, EMP E2, EMP E3, DEPT D1, DEPT D2, DEPT D3
WHERE E1.MGR = E2.EMPNO
AND E2.MGR = E3.EMPNO
AND E1.DEPTNO = D1.DEPTNO
AND E2.DEPTNO = D2.DEPTNO
AND E3.DEPTNO = D3.DEPTNO
AND E1.DEPTNO = 10
AND E2.JOB IN ('MANAGER', 'PRESIDENT')
AND E3.SAL >= E2.SAL;