-- 01
SELECT ENAME
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'ADAMS');

-- 02
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL
            FROM EMP
            WHERE ENAME = 'KING');


-- 03
SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'JONES')
AND ENAME != 'JONES';

-- 04
SELECT ENAME, JOB
FROM EMP
WHERE JOB = (SELECT JOB
            FROM EMP
            WHERE ENAME = 'JAMES')
AND ENAME != 'JAMES';

-- 05
SELECT EMPNO, ENAME, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
                      FROM EMP
                      WHERE ENAME = 'WARDS');

-- 06
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP
                  WHERE ENAME = 'SCOTT');

-- 07
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE
                  FROM EMP
                  WHERE JOB = 'PRESIDENT');

-- 08
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL
            FROM EMP
            WHERE EMPNO = 7839);

-- 09
SELECT *
FROM EMP
WHERE HIREDATE < (SELECT HIREDATE
                  FROM EMP
                  WHERE ENAME = 'MILLER');

-- 10
SELECT ENAME, EMPNO
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'ALLEN');

-- 11
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'MILLER')
AND SAL < (SELECT SAL
          FROM EMP
          WHERE ENAME = 'ALLEN');

-- 12
SELECT *
FROM EMP
WHERE DEPTNO = 20
AND JOB = (SELECT JOB
          FROM EMP
          WHERE ENAME = 'SMITH')
AND ENAME != 'SMITH';

-- 13
SELECT *
FROM EMP
WHERE JOB = 'MANAGER'
AND DEPTNO = (SELECT DEPTNO
              FROM EMP
              WHERE ENAME = 'TURNER');

-- 14
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE > '31-12-1980'
AND HIREDATE < (SELECT HIREDATE
                FROM EMP
                WHERE ENAME = 'KING');

-- 15
SELECT ENAME, SAL, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE SAL < (SELECT SAL
            FROM EMP
            WHERE ENAME = 'BLAKE')
AND SAL > 3500;

-- 16
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'SCOTT')
AND SAL < (SELECT SAL
          FROM EMP
          WHERE ENAME = 'KING');

-- 17
SELECT ENAME
FROM EMP
WHERE ENAME LIKE 'A%'
AND DEPTNO = (SELECT DEPTNO
              FROM EMP
              WHERE ENAME = 'BLAKE');

-- 18
SELECT ENAME, COMM
FROM EMP
WHERE COMM IS NOT NULL AND COMM > 0
AND JOB = (SELECT JOB
          FROM EMP
          WHERE ENAME = 'SMITH');

-- 19
SELECT *
FROM EMP
WHERE JOB = 'CLERK'
AND DEPTNO = (SELECT DEPTNO
              FROM EMP
              WHERE ENAME = 'TURNER');

-- 20
SELECT ENAME, SAL, JOB
FROM EMP
WHERE SAL*12 > (SELECT SAL*12
                FROM EMP
                WHERE ENAME = 'SMITH')
AND SAL*12 < (SELECT SAL*12
              FROM EMP
              WHERE ENAME = 'KING');

-- 21
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'SMITH');

-- 22
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'KING');

-- 23
SELECT LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE EMPNO = 7902);

-- 24
SELECT DNAME, LOC, DEPTNO
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE ENAME LIKE '%R');

-- 25
SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE JOB = 'PRESIDENT');

-- 26
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'ACCOUNTING');

-- 27
SELECT ENAME, SAL
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM DEPT
                WHERE LOC = 'CHICAGO');

-- 28
SELECT *
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'SALES');

-- 29
SELECT EMP.*, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE LOC = 'NEW YORK');

-- 30
SELECT ENAME
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'OPERATIONS');

-- 31
SELECT ENAME
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'SCOTT')
AND DEPTNO = (SELECT DEPTNO
              FROM DEPT
              WHERE DNAME = 'ACCOUNTING');

-- 32
SELECT *
FROM EMP
WHERE JOB = 'MANAGER'
AND DEPTNO = (SELECT DEPTNO
              FROM DEPT
              WHERE LOC = 'CHICAGO');

-- 33
SELECT ENAME, SAL
FROM EMP
WHERE SAL > (SELECT SAL
            FROM EMP
            WHERE ENAME = 'KING')
AND DEPTNO = (SELECT DEPTNO
              FROM DEPT
              WHERE DNAME = 'ACCCOUNTING');

-- 34
SELECT *
FROM EMP
WHERE JOB = 'SALESMAN'
AND DEPTNO = (SELECT DEPTNO
              FROM DEPT
              WHERE DNAME = 'SALES');

-- 35
SELECT ENAME, SAL, JOB, HIREDATE
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME = 'OPERATIONS')
AND HIREDATE < (SELECT HIREDATE
                FROM EMP
                WHERE ENAME = 'KING');

-- 36
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME LIKE '%S');

-- 37
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE ENAME LIKE '%A%');

-- 38
SELECT DNAME, LOC
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE SAL = 800);

-- 39
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE COMM IS NOT NULL AND COMM > 0);

-- 40
SELECT LOC
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE COMM IS NOT NULL AND COMM > 0
                AND DEPTNO = 40);

-- 41
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MAX(SAL)
            FROM EMP);

-- 42
SELECT ENAME
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
            FROM EMP);

-- 43
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE)
                  FROM EMP);

-- 44
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE = (SELECT MAX(HIREDATE)
                  FROM EMP);

-- 45
SELECT ENAME, COMM
FROM EMP
WHERE COMM = (SELECT MIN(COMM)
              FROM EMP);

-- 46
SELECT ENAME, SAL, COMM
FROM EMP
WHERE COMM = (SELECT MAX(COMM)
              FROM EMP);

-- 47
SELECT *
FROM EMP
WHERE EMPNO = (SELECT MAX(EMPNO)
              FROM EMP);

-- 48
SELECT *
FROM EMP
WHERE HIREDATE = (SELECT MIN(HIREDATE)
                  FROM EMP);

-- 49
SELECT *
FROM EMP
WHERE SAL = (SELECT MIN(SAL)
                  FROM EMP);

-- 50
SELECT ENAME, SAL*12 AS "ANNUAL SALARY"
FROM EMP
WHERE SAL*12 > ALL (SELECT SAL*12
                FROM EMP
                WHERE JOB = 'SALESMAN');

-- 51
SELECT ENAME
FROM EMP
WHERE SAL > ALL (SELECT SAL
                FROM EMP
                WHERE JOB = 'SALESMAN');

-- 52
SELECT *
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE
                      FROM EMP
                      WHERE JOB = 'CLERK');

-- 53
SELECT ENAME, SAL
FROM EMP
WHERE SAL < ANY (SELECT SAL
                FROM EMP
                WHERE JOB = 'MANAGER');

-- 54
SELECT ENAME, HIREDATE
FROM EMP
WHERE HIREDATE < ALL (SELECT HIREDATE
                      FROM EMP
                      WHERE JOB = 'MANAGER');

-- 55
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE
                      FROM EMP
                      WHERE JOB = 'MANAGER')
AND SAL > ALL (SELECT SAL
              FROM EMP
              WHERE JOB = 'CLERK');

-- 56
SELECT *
FROM EMP
WHERE JOB = 'CLERK'
AND HIREDATE < ANY (SELECT HIREDATE
                    FROM EMP
                    WHERE JOB = 'SALESMAN');

-- 57
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM DEPT
                WHERE DNAME IN ('ACCOUNTING', 'SALES'));

-- 58
SELECT DNAME
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE ENAME IN ('SMITH', 'KING', 'MILLER'));

-- 59
SELECT *
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM DEPT
                WHERE LOC IN ('NEW YORK', 'CHICAGO'));

-- 60
SELECT ENAME
FROM EMP
WHERE HIREDATE > ALL (SELECT HIREDATE
                      FROM EMP
                      WHERE DEPTNO = 10);



